# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.recommend_service_pb2 as recommend__service__pb2


class RecommendationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnimeRecommendations = channel.unary_unary(
                '/maki.RecommendationService/GetAnimeRecommendations',
                request_serializer=recommend__service__pb2.WatchedAnime.SerializeToString,
                response_deserializer=recommend__service__pb2.RecommendedAnime.FromString,
                )


class RecommendationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAnimeRecommendations(self, request, context):
        """Get a list of reccomendations based on the user list given as input
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnimeRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnimeRecommendations,
                    request_deserializer=recommend__service__pb2.WatchedAnime.FromString,
                    response_serializer=recommend__service__pb2.RecommendedAnime.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maki.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecommendationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAnimeRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/maki.RecommendationService/GetAnimeRecommendations',
            recommend__service__pb2.WatchedAnime.SerializeToString,
            recommend__service__pb2.RecommendedAnime.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
