# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommend_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17recommend_service.proto\x12\x04maki\"\x12\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\r\",\n\x0fRecommendedItem\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05score\x18\x02 \x01(\x02\"?\n\x0cWatchedAnime\x12\x19\n\x05items\x18\x01 \x03(\x0b\x32\n.maki.Item\x12\x0e\n\x01k\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x04\n\x02_k\"8\n\x10RecommendedAnime\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.maki.RecommendedItem2^\n\x15RecommendationService\x12\x45\n\x17GetAnimeRecommendations\x12\x12.maki.WatchedAnime\x1a\x16.maki.RecommendedAnimeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommend_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ITEM']._serialized_start=33
  _globals['_ITEM']._serialized_end=51
  _globals['_RECOMMENDEDITEM']._serialized_start=53
  _globals['_RECOMMENDEDITEM']._serialized_end=97
  _globals['_WATCHEDANIME']._serialized_start=99
  _globals['_WATCHEDANIME']._serialized_end=162
  _globals['_RECOMMENDEDANIME']._serialized_start=164
  _globals['_RECOMMENDEDANIME']._serialized_end=220
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=222
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=316
# @@protoc_insertion_point(module_scope)
